fix(docs): correct Storybook links to use external URL
Fix broken links in typography documentation that were causing Docusaurus build to fail.
Changed relative  links to absolute external URL

Error: Docusaurus found broken links!
- /docs/tokens/typography -> /storybook/?path=/story/tokens-typography--extended-type-scale

Fixes Check-lint CI failure.